### ISSUE TITLE
What does Healpix pooling return?

### ISSUE THREAD

**Issue by Kannan-Balakrishnan** [deepsphere/deepsphere-pytorch#11]
Hey. Thanks for the great research work on spherical graphs. I am trying to adapt the code for spherical images. 
Coming to my question, You mentioned that the Healpix pooling requires the pixel to be in Nested Ordering. I wanted to ask you, what will be the ordering of the pixel (Ring or Nested?) after Healpix pooling is done on the spherical Graph.

Thanks.

**Comment by mdeff** [comment]
Hey. Thanks for your interest and kind words!

Pooling won't change the ordering. It will stay nested. (If need be, you can reorder between ring and nested whenever you want.)

Looking forward to see your work on spherical images!
